let ASSETS=[];
const DATA_ENDPOINT="https://dnrwntvjjzaokhiwxsvv.supabase.co/functions/v1/cre-public-v2";
const SUMMARY={"generated":"2026-09-01","sourceSnapshot":"2026-07-17","siteRefresh":"2026-09-01","total":1485,"multifamily":1485,"fiftyPlus":756,"unitsFiftyPlus":102342,"withMao":368,"withContactPath":210,"priorities":{"Underwrite next":27,"Watch":167,"Research gap":1209,"Resolve contact":19,"Monitor":63,"Call now":0},"confidence":{"A/B":24,"D/X":1457,"C":4},"healthFindings":[{"severity":"critical","code":"NO_SIGNAL_HISTORY","message":"Only one dated source snapshot exists, so week-over-week change signals cannot yet operate as designed."},{"severity":"critical","code":"STALE_SOURCE","message":"The underlying source observation is 46 days old even though the v2 application was refreshed September 1."},{"severity":"high","code":"CITY_ZIP_FIELD_CONTAMINATION","message":"At least 158 city rows use a clearly non-local ZIP in the property ZIP field."},{"severity":"critical","code":"MAO_PRECISION_EXCEEDS_EVIDENCE","message":"Most legacy MAOs rely on tract-median rent proxies; v2 now gates them behind confidence and scenario ranges."},{"severity":"high","code":"VALUATION_OUTLIERS","message":"91 legacy MAOs exceed 2x appraised value and remain explicitly flagged for review."},{"severity":"medium","code":"LEGACY_SCORE_REPLACED","message":"The former 50/50 average is preserved only for reference; v2 ranks motivation, economics, executability and confidence separately."},{"severity":"high","code":"CONTACT_COVERAGE_GAP","message":"Decision-path evidence exists for 210 assets, but normalized verified contact records still require protected enrichment."}],"sources":[{"name":"St. Louis County Assessor","status":"stale","coverage":"491 enriched records","lastSuccess":"2026-07-17","cadence":"Weekly","issue":"46 days since source snapshot"},{"name":"St. Louis City Assessor","status":"warning","coverage":"994 thin-file records","lastSuccess":"2026-07-17","cadence":"Weekly","issue":"158 probable property-ZIP contamination records"},{"name":"HUD / FHA","status":"warning","coverage":"61 assisted assets","lastSuccess":"2026-07-17","cadence":"Monthly","issue":"Snapshot-only; no change history"},{"name":"LIHTC","status":"warning","coverage":"78 tagged assets","lastSuccess":"2026-07-17","cadence":"Quarterly","issue":"Year-15 status not continuously refreshed"},{"name":"Public reviews","status":"warning","coverage":"20 verified matches","lastSuccess":"2026-07-17","cadence":"Monthly","issue":"Limited verified match coverage"},{"name":"Recorder / debt","status":"warning","coverage":"Selective records","lastSuccess":"2026-07-17","cadence":"On demand","issue":"Recorder verification still required on many assets"},{"name":"Aule v2 sanitized cache","status":"healthy","coverage":"1,485 records","lastSuccess":"2026-09-01","cadence":"On refresh","issue":"No public phone or email fields"}]};
const ICON={pulse:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 17h3l3-9 4 12 3-7h3"/></svg>',lock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>',clock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/></svg>'};
const state={page:'today',view:'table',preset:'actionable',search:'',filters:{minUnits:50,maxUnits:null,jurisdiction:'',zip:'',minScore:null,minConfidence:null,mao:false,contact:false,signal:false,clean:false,priority:''},sort:'score',sortDir:'desc',selected:null};
let saved=new Set(JSON.parse(localStorage.getItem('aule-cre-saved')||'[]'));
const fmt=new Intl.NumberFormat('en-US'); const money=(n,compact=false)=>{if(!n)return '—';if(compact&&n>=1e6)return '$'+(n/1e6).toFixed(n>=1e7?1:2)+'M';if(compact&&n>=1e3)return '$'+Math.round(n/1e3)+'K';return '$'+fmt.format(Math.round(n))};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function grade(v){return v>=80?'A':v>=65?'B':v>=50?'C':'D'}
function tierClass(p){return 'tier-'+({ 'Call now':'call','Underwrite next':'underwrite','Resolve contact':'contact','Research gap':'research','Watch':'watch','Monitor':'monitor'}[p]||'monitor')}
function statusClass(s){return s==='Defensible range'?'status-defensible':s==='Directional range'?'status-directional':'status-not'}
function contactClass(s){return s==='Ready'?'contact-ready':s==='Mgmt path'?'contact-mgmt':'contact-needs'}
function getFiltered(ignorePreset=false){let r=ASSETS.filter(a=>{
 const f=state.filters;if(f.minUnits!=null&&a.units<f.minUnits)return false;if(f.maxUnits!=null&&a.units>f.maxUnits)return false;if(f.jurisdiction&&a.jurisdiction!==f.jurisdiction)return false;if(f.zip&&!a.zip.startsWith(f.zip))return false;if(f.minScore!=null&&a.score.overall<f.minScore)return false;if(f.minConfidence!=null&&a.score.confidence<f.minConfidence)return false;if(f.mao&&a.underwriting.status==='Not underwritable yet')return false;if(f.contact&&a.contactStatus==='Needs resolution')return false;if(f.signal&&a.signals.length<2)return false;if(f.clean&&a.warnings.length)return false;if(f.priority&&a.score.priority!==f.priority)return false;
 if(state.search){const q=state.search.toLowerCase();const hay=[a.name,a.address,a.city,a.zip,a.owner,a.ownerType,a.signalText,a.structure,a.debtStatus].join(' ').toLowerCase();if(!hay.includes(q))return false}return true});
 if(!ignorePreset){if(state.preset==='actionable')r=r.filter(a=>['Call now','Underwrite next','Resolve contact'].includes(a.score.priority));if(state.preset==='high')r=r.filter(a=>a.score.overall>=60);if(state.preset==='mao')r=r.filter(a=>a.underwriting.status!=='Not underwritable yet');if(state.preset==='skip')r=r.filter(a=>a.contactStatus==='Needs resolution'&&a.score.motivation>=45);if(state.preset==='gaps')r=r.filter(a=>a.score.priority==='Research gap');if(state.preset==='new')r=r.filter(a=>a.signals.length>=2);}
 const mul=state.sortDir==='desc'?-1:1;r.sort((a,b)=>{let av,bv;if(state.sort==='score'){av=a.score.overall;bv=b.score.overall}else if(state.sort==='units'){av=a.units;bv=b.units}else if(state.sort==='mao'){av=a.underwriting.base;bv=b.underwriting.base}else if(state.sort==='confidence'){av=a.score.confidence;bv=b.score.confidence}else{av=a.name;bv=b.name}return(av>bv?1:av<bv?-1:0)*mul});return r}
function setCrumb(title,kicker='Acquisition workspace'){document.getElementById('crumb-title').textContent=title;document.getElementById('crumb-kicker').textContent=kicker}
function go(page){state.page=page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){const p=document.getElementById('page');if(state.page==='today'){setCrumb('Today');p.innerHTML=renderToday()}else if(state.page==='discover'){setCrumb('Discover','Research universe');p.innerHTML=renderDiscover()}else if(state.page==='signals'){setCrumb('Signals','Change intelligence');p.innerHTML=renderSignals()}else if(state.page==='underwrite'){setCrumb('Underwrite','Acquisition economics');p.innerHTML=renderUnderwrite()}else if(state.page==='outreach'){setCrumb('Outreach','Decision-path queue');p.innerHTML=renderOutreach()}else if(state.page==='saved'){setCrumb('Saved','Shortlist');p.innerHTML=renderSaved()}else{setCrumb('Data health','System integrity');p.innerHTML=renderHealth()}updateNav()}
function pageHead(kicker,title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div><div class="head-actions">${actions}</div></div>`}
function metric(label,value,note){return `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`}
function actionRow(a){return `<div class="action-row" onclick="openAsset('${a.id}')"><div class="score-orb">${a.score.overall}</div><div class="asset-main"><b>${esc(a.name)}</b><span>${a.units} units · ${esc(a.city||a.jurisdiction)} · ${esc(a.score.why.motivation[0]||'Research record')}</span></div><div class="mini-money"><b>${money(a.underwriting.base,true)}</b><span>${a.underwriting.status==='Not underwritable yet'?'research band':'base MAO'}</span></div><div class="tier ${tierClass(a.score.priority)}">${a.score.priority}</div><div class="arrow">›</div></div>`}